name: kido
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  

dependencies:
  flame: ^1.0.0-releasecandidate.11
  firebase_auth: ^0.18.4+1
  firebase_core : ^0.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "images/1.jpeg"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  
  uses-material-design: true

  assets:
    - images/1.jpeg
    - images/2.jpeg
    - images/3.png